name: tower_rpg
description: Un RPG tour par étage avec quêtes, équipement et arbre de talents.
publish_to: "none"
version: 0.3.0+1

environment:
 sdk: ">=3.0.0 <4.0.0"

dependencies:
 flutter:
   sdk: flutter

 cupertino_icons: ^1.0.5

dev_dependencies:
 flutter_test:
   sdk: flutter
 flutter_lints: ^2.0.0

flutter:
 uses-material-design: true

 assets:
   - assets/sprites/player_male.png
   - assets/sprites/player_female.png
   - assets/sprites/monster_lezard.png
   - assets/sprites/monster_gobelin.png
   - assets/tiles/floor.png
   - assets/tiles/wall.png
   - assets/tiles/door.png 
