name: Flutter CI

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 build:
   name: Build Flutter App
   runs-on: macos-latest

   steps:
   - uses: actions/checkout@v3

   - name: Set up Flutter
     uses: subosito/flutter-action@v2
     with:
       flutter-version: '3.13.0'

   - name: Install dependencies
     run: flutter pub get

   - name: Analyze code
     run: flutter analyze

   - name: Run tests
     run: flutter test

   - name: Build iOS
     run: flutter build ios --no-codesign

   - name: Build Android
     run: flutter build apk --release
