name: Flutter iOS Build & Download Link

on:
 push:
   branches:
     - main
 pull_request:

jobs:
 build-ios:
   runs-on: macos-latest

   steps:
   # 1️⃣ Cloner le repo
   - name: Checkout repository
     uses: actions/checkout@v3

   # 2️⃣ Installer Flutter
   - name: Setup Flutter
     uses: subosito/flutter-action@v2
     with:
       flutter-version: '3.13.0' # Mets ta version exacte

   # 3️⃣ Activer iOS si manquant
   - name: Enable iOS platform
     run: flutter create . --platforms=ios

   # 4️⃣ Installer les dépendances Flutter
   - name: Flutter pub get
     run: flutter pub get

   # 5️⃣ Installer les Pods iOS
   - name: Install CocoaPods
     run: |
       cd ios
       pod install
       cd ..

   # 6️⃣ Créer un ExportOptions.plist minimal
   - name: Create ExportOptions.plist
     run: |
       cat <<EOF > ios/ExportOptions.plist
       <?xml version="1.0" encoding="UTF-8"?>
       <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
       <plist version="1.0">
       <dict>
         <key>method</key>
         <string>development</string>
         <key>signingStyle</key>
         <string>manual</string>
         <key>compileBitcode</key>
         <false/>
         <key>destination</key>
         <string>export</string>
         <key>stripSwiftSymbols</key>
         <true/>
         <key>teamID</key>
         <string>XXXXXXXXXX</string>
       </dict>
       </plist>
       EOF

   # 7️⃣ Build iOS sans codesign
   - name: Build iOS
     run: flutter build ios --release --no-codesign

   # 8️⃣ Créer l’IPA
   - name: Create .ipa
     run: |
       mkdir -p build/ios/ipa
       xcodebuild -workspace ios/Runner.xcworkspace \
                  -scheme Runner \
                  -configuration Release \
                  -archivePath build/ios/Runner.xcarchive archive
       xcodebuild -exportArchive \
                  -archivePath build/ios/Runner.xcarchive \
                  -exportOptionsPlist ios/ExportOptions.plist \
                  -exportPath build/ios/ipa

   # 9️⃣ Uploader l’IPA
   - name: Upload IPA
     id: upload
     uses: actions/upload-artifact@v4
     with:
       name: Runner-ipa
       path: build/ios/ipa/Runner.ipa
       overwrite: true

   # 🔟 Afficher le lien direct
   - name: Display IPA download link
     run: echo "Lien direct IPA : ${{ steps.upload.outputs.artifact-url }}"
