name: Flutter Web Build

on:
 push:
   branches:
     - main
 pull_request:

jobs:
 build-web:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Setup Flutter
       uses: subosito/flutter-action@v2
       with:
         flutter-version: '3.13.0'  # adapte si besoin

     - name: Flutter pub get
       run: flutter pub get

     - name: Build Flutter Web
       run: flutter build web --release

     - name: Upload Web artifact
       uses: actions/upload-artifact@v4
       with:
         name: web-build
         path: build/web
         overwrite: true
