name: Flutter iOS Build

on:
 push:
   branches:
     - main
 pull_request:

jobs:
 build-ios:
   runs-on: macos-latest

   steps:
   # 1️⃣ Cloner le repo
   - name: Checkout repository
     uses: actions/checkout@v3

   # 2️⃣ Installer Flutter
   - name: Setup Flutter
     uses: subosito/flutter-action@v2
     with:
       flutter-version: '3.13.0' # adapte si ta version est différente

   # 3️⃣ Installer les dépendances
   - name: Flutter pub get
     run: flutter pub get

   # 4️⃣ Générer le build iOS en release
   - name: Build iOS
     run: flutter build ios --release --no-codesign

   # 5️⃣ Archiver en .ipa
   - name: Create .ipa
     run: |
       mkdir -p build/ios/ipa
       xcodebuild -workspace ios/Runner.xcworkspace \
                  -scheme Runner \
                  -configuration Release \
                  -archivePath build/ios/Runner.xcarchive archive
       xcodebuild -exportArchive \
                  -archivePath build/ios/Runner.xcarchive \
                  -exportOptionsPlist ios/ExportOptions.plist \
                  -exportPath build/ios/ipa

   # 6️⃣ Uploader l’artefact avec v4
   - name: Upload IPA
     uses: actions/upload-artifact@v4
     with:
       name: Runner-ipa
       path: build/ios/ipa/Runner.ipa
       overwrite: true
